### ISSUE TITLE
Client already exist

### ISSUE THREAD

**Issue by albertopicca** [ppatierno/gnatmq#1]
During some tests with PLC ( eg . Siemens , Wago ) I noticed that the name of the client , is always the same for every request sent CONN .
The broker , on line 303 of MqttBroker.cs occurs if there is already a client of the same name and destroys the channel .

In fact , the PLC opens n - client , at different times, very quickly, and the broker closes the socket . The PLC tries to reopen the connection , but the broker closes again because there is already a client of the same name .
From the PLC connections exits, with the same name, with the same IP address but with different local ports each time .

You might think of doing verification if the customer already exists with the same but with the same IP address and the same port ?

What do you think ?

Thanks
Alberto

**Comment by ppatierno** [comment]
The official MQTT 3.1.1 standard says : 

"If the ClientId represents a Client already connected to the Server then the Server MUST disconnect the existing Client"

You can read it here : http://docs.oasis-open.org/mqtt/mqtt/v3.1.1/mqtt-v3.1.1.pdf
On page 30 related to the broker response to the CONNECT packet.

Thanks,
Paolo.

**Comment by albertopicca** [comment]
Thanks for your answer.
Alberto
