### ISSUE TITLE
Embeddable MQTT broker 

### ISSUE THREAD

**Issue by VladimirAkopyan** [ppatierno/gnatmq#18]
We are modifying Gnatmq to embed it inside a larger application. Inside the mqttBroker class
We made the 
`void Client_MqttMsgPublishReceived(object sender, MqttMsgPublishEventArgs e)`
Raise an an event to the external application, and we made the method
`public void PublishData(string topic, byte[] data, bool retain = true, byte qos = MqttMsgBase.QOS_LEVEL_AT_LEAST_ONCE)`
public. 
Will this cause issues with threading?

**Comment by VladimirAkopyan** [comment]
`        void Client_MqttMsgPublishReceived(object sender, MqttMsgPublishEventArgs e)
        {
            MqttClient client = (MqttClient)sender;

            //Fires an event
                Task.Run(() =>
                {
                    //Creates a thing to pass to the event handler. 
                    var data = new M2Mqtt.Integration.MqttMesageRecievedEvent(client.ClientId,
                        e.Topic, e.Message, false, e.QosLevel, e.Retain);
                    //check if anyone is subscribed to the event,, and invokes. If not, then it;s null.
                    System.Threading.Interlocked.CompareExchange(ref MqttMessageRecieved, null, null)?
                        .Invoke(this, data);
                });

            // create PUBLISH message to publish
            // [v3.1.1] DUP flag from an incoming PUBLISH message is not propagated to subscribers
            //          It should be set in the outgoing PUBLISH message based on transmission for each subscriber
            MqttMsgPublish publish = new MqttMsgPublish(e.Topic, e.Message, false, e.QosLevel, e.Retain);
            
            // publish message through publisher manager
            this.publisherManager.Publish(publish);
        }`

This seems to cause thousands of  Task<Windows.Storage.Streams.IBuffer> to spawn at a rate of ~12 per second, and stay in the heap indefinitely. Why would that happen? 
The device is receiving messages at a rate of 7 per second.

**Comment by VladimirAkopyan** [comment]
Actually, even if I comment out that code, the items seem to build up anyway. Could this actually be MQTT, or is it something unrelated? 
![image](https://cloud.githubusercontent.com/assets/12278048/13716364/823c98c0-e7d2-11e5-9eb3-0c269028e236.png)

**Comment by GioviQ** [comment]
The same happens to me, so in MqttClient.cs I added a little delay in OnInternalEvent method. It is not the best solution, but in my case it works.

```
void Client_MqttMsgPublishReceived(object sender, MqttMsgPublishEventArgs e)
        {
            MqttClient client = (MqttClient)sender;

            // create PUBLISH message to publish
            // [v3.1.1] DUP flag from an incoming PUBLISH message is not propagated to subscribers
            //          It should be set in the outgoing PUBLISH message based on transmission for each subscriber
            MqttMsgPublish publish = new MqttMsgPublish(e.Topic, e.Message, false, e.QosLevel, e.Retain);

            // publish message through publisher manager
            this.publisherManager.Publish(publish);

            //My custom function delegate (do not create threads, it is too expensive)
            if (SaveMessage != null)
                this.SaveMessage(e);
        }

```
  ```
private void OnInternalEvent(InternalEvent internalEvent)
        {
            lock (this.eventQueue)
            {
                this.eventQueue.Enqueue(internalEvent);
            }

            this.receiveEventWaitHandle.Set();

            Thread.Sleep(50); //change 50 as needed. Check in DispatchEventThread
                        //this.eventQueue.Count with #if TRACE
                       // MqttUtility.Trace.WriteLine(TraceLevel.Verbose, "eventQueue count {0}",          
                      //this.eventQueue.Count);
                      //#endif
        }
```

**Comment by VladimirAkopyan** [comment]
Thank you! Will give it a try asap

**Comment by VladimirAkopyan** [comment]
I now believe the excessive memory usage is caused by the debugger. 
We have used the Broker for weeks in release mode and have not encountered this problem in production.
