### ISSUE TITLE
Dead?

### ISSUE THREAD

**Issue by HakanL** [ppatierno/gnatmq#26]
Is this project dead? No commits since Dec 2015.

**Comment by VladimirAkopyan** [comment]
It's not being actively developed, but it works quite well. We've put this library through a lot, stuffed it into a UWP app and it held up really well during many months of operation.

**Comment by HakanL** [comment]
Ok, thanks. Would you be interested in adding another contributor who can accept pull requests, etc? Would be good to accept enhancements, etc.

**Comment by VladimirAkopyan** [comment]
I am not in charge of the project, but yes.

**Comment by JTrotta** [comment]
This project has been moved [here:.]( https://github.com/eclipse/paho.mqtt.m2mqtt) This repository is no longer updated.

**Comment by ppatierno** [comment]
@HakanL @VladimirAkopyan @JTrotta just read here : https://paolopatierno.wordpress.com/2016/08/21/m2mqtt-and-gnatmq-are-dead-long-life-to-them/ and thanks for your support !

**Comment by HakanL** [comment]
So if I read this correctly this is still the right place for GnatMQ, it's the client library that's been moved, right? And thanks @ppatierno for clarifying in your blog post.
