### ISSUE TITLE
bug in GnatMQ\Managers\MqttSubscriberManager.cs

### ISSUE THREAD

**Issue by Jeff17Robbins** [ppatierno/gnatmq#7]
The problem seems to be in the last line of GetSubscription:

```
return query.Distinct(comparer).First();
```

If the query.Distinct(comparer) comes back empty, the .First() throws an error.

Perhaps 
```
return query.Distinct(comparer).FirstOrDefault();
```
would be the fix?

**Comment by Jeff17Robbins** [comment]
I see that someone else already found this bug

https://github.com/GioviQ/gnatmq/commit/b7ba5f799c229693a34dd0095309bd8effdbd833

**Comment by ppatierno** [comment]
Just merged the pull request. Bug fixed. Thanks.
