### ISSUE TITLE
$SYS

### ISSUE THREAD

**Issue by AngeloBestetti** [ppatierno/gnatmq#9]
Ciao Paolo, come stai?

Angelo from brazil here, I´m using your gnatmq on our solution with no problems at all. I don´t know if I´m wrong but I didn´t see any implementation of $SYS topic. When I connect using MQTT.fx I can subscribe $SYS but do not receive any counters. It´s that correct?

**Comment by ppatierno** [comment]
Yes you're right no $SYS topic implementation for now.
